#!/usr/bin/env php
<?php
// парсим файл конфигурации
$config = parse_ini_file("config.ini", true);

require_once("./vendor/autoload.php");

use pulyavin\wmkeeper\Commands;
use pulyavin\wmkeeper\Shell;
use pulyavin\wmxml\WMXml as WMXml;
use pulyavin\console\Console as Console;
use baibaratsky\WebMoney\Signer as Signer;

try {
	// будем работать с классом Signer на PHP
	if (
		isset($config['main']['key_file'])
		&&
		isset($config['main']['key_password'])
	) {
		$wmsigner = new Signer($config['main']['wmid'], $config['main']['key_file'], $config['main']['key_password']);
	}
	// бинарный подписчик
	else {
		$wmsigner = $config['paths']['wmsigner'];
	}

	// создаём объект WebMoney XML API
	$wmxml = new WMXml(
		"classic",
		[
			"wmid"     => $config['main']['wmid'],
			"wmsigner" => $wmsigner,
			"tranid"  => $config['paths']['tranid'],
			"connect"  => $config['curl']['connect'],
			"timeout"  => $config['curl']['timeout']
		]
	);

	// создаём объект ядра комманд
	$commands = new Commands($wmxml, $config);

	//создаём объект консоли
	$console = new Console();

	// запускаем shell
    Shell::init($commands, $console)->start();
} catch (Exception $e) {
	echo $e->getMessage();
}