DROP TABLE IF EXISTS "bl";
CREATE TABLE "bl" ("time" INTEGER PRIMARY KEY  NOT NULL  UNIQUE , "rank" INTEGER);
DROP TABLE IF EXISTS "events";
CREATE TABLE "events" ("id" INTEGER NOT NULL , "time" INTEGER NOT NULL , "is_hidden" INTEGER NOT NULL , "type" INTEGER NOT NULL , "description" TEXT NOT NULL , "expiration" INTEGER);
DROP TABLE IF EXISTS "invoices";
CREATE TABLE "invoices" ("id" INTEGER NOT NULL , "orderid" INTEGER, "storewmid" VARCHAR NOT NULL , "storepurse" VARCHAR NOT NULL , "amount" DOUBLE NOT NULL , "datecrt" INTEGER NOT NULL , "dateupd" INTEGER NOT NULL , "state" INTEGER NOT NULL , "address" TEXT, "description" TEXT, "period" INTEGER, "expiration" INTEGER, "wmtranid" INTEGER);
DROP TABLE IF EXISTS "outvoices";
CREATE TABLE "outvoices" ("id" INTEGER PRIMARY KEY  NOT NULL , "orderid" INTEGER, "storepurse" VARCHAR NOT NULL , "customerwmid" VARCHAR NOT NULL , "customerpurse" VARCHAR NOT NULL , "amount" DOUBLE NOT NULL , "datecrt" INTEGER NOT NULL , "dateupd" INTEGER NOT NULL , "state" INTEGER NOT NULL , "address" TEXT, "description" TEXT, "period" INTEGER, "expiration" INTEGER, "wmtranid" INTEGER);
DROP TABLE IF EXISTS "purses";
CREATE TABLE "purses" ("id" INTEGER PRIMARY KEY  NOT NULL  UNIQUE , "pursename" VARCHAR NOT NULL , "description" VARCHAR, "amount" DOUBLE NOT NULL , "amount_last" DOUBLE);
DROP TABLE IF EXISTS "purses_times";
CREATE TABLE "purses_times" ("pursename" VARCHAR NOT NULL ,"time" INTEGER NOT NULL  DEFAULT (0) ,"xml_id" INTEGER NOT NULL );
DROP TABLE IF EXISTS "system";
CREATE TABLE "system" ("name" VARCHAR PRIMARY KEY  NOT NULL  UNIQUE , "value" TEXT);
DROP TABLE IF EXISTS "tl";
CREATE TABLE "tl" ("time" INTEGER PRIMARY KEY  NOT NULL  UNIQUE , "rank" INTEGER);
DROP TABLE IF EXISTS "transactions";
CREATE TABLE "transactions" ("id" INTEGER NOT NULL , "pursesrc" VARCHAR NOT NULL , "pursedest" VARCHAR NOT NULL , "purse" VARCHAR NOT NULL , "corrpurse" VARCHAR NOT NULL , "type" VARCHAR NOT NULL , "amount" DOUBLE NOT NULL , "comiss" DOUBLE NOT NULL , "opertype" INTEGER NOT NULL , "wminvid" INTEGER, "orderid" INTEGER, "tranid" INTEGER NOT NULL , "period" INTEGER, "description" TEXT, "datecrt" INTEGER NOT NULL , "dateupd" INTEGER NOT NULL , "corrwm" VARCHAR NOT NULL , "rest" DOUBLE NOT NULL );
DROP TABLE IF EXISTS "userinfo";
CREATE TABLE "userinfo" ("name" VARCHAR PRIMARY KEY  NOT NULL  UNIQUE , "value" TEXT);
